root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/hat ./cmd/hat"
bin = "tmp/hat"
include_ext = ["go","tpl","tmpl","html"]
exclude_dir = ["tmp","spec","sdk/internal/sample-client"]
delay = 1000
stop_on_error = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[log]
time = true

[env]
PORT = "8080"
GOPROXY = "https://proxy.golang.org"

