INSERT INTO bowclass (name, code) VALUES
('Cub Male Freestyle Limited Recurve', 'CMFS-R'),
('Cub Male Bowhunter Recurve', 'CMBHR'),
('Cub Female Bowhunter Recurve', 'CFBHR'),
('Junior Male Longbow', 'JMLB'),
('Junior Male Traditional Recurve', 'JMTR'),
('Junior Female Traditional Recurve', 'JFTR'),
('Junior Male Bowhunter Recurve', 'JMBHR'),
('Junior Female Bowhunter Recurve', 'JFBHR'),
('Junior Female Bowhunter Unlimited', 'JFBU'),
('Adult Male Historical Bow', 'AMHB'),
('Adult Female Historical Bow', 'AFHB'),
('Adult Male Longbow', 'AMLB'),
('Adult Female Longbow', 'AFLB'),
('Veteran Male Longbow', 'VMLB'),
('Veteran Female Longbow', 'VFLB'),
('Senior Male Longbow', 'SMLB'),
('Adult Male Freestyle Unlimited', 'AMFU'),
('Adult Female Freestyle Unlimited', 'AFFU'),
('Veteran Male Freestyle Unlimited', 'VMFU'),
('Senior Male Freestyle Unlimited', 'SMFU'),
('Veteran Male Freestyle Limited Recurve', 'VMFSR'),
('Adult Male Barebow Recurve', 'AMBBR'),
('Veteran Male Barebow Recurve', 'VMBBR'),
('Young Adult Male Traditional Recurve', 'YAMTR'),
('Young Adult Female Traditional Recurve', 'YAFTR'),
('Adult Male Traditional Recurve', 'AMTR'),
('Adult Female Traditional Recurve', 'AFTR'),
('Veteran Male Traditional Recurve', 'VMTR'),
('Veteran Female Traditional Recurve', 'VFTR'),
('Young Adult Female Bowhunter Recurve', 'YAFBHR'),
('Adult Male Bowhunter Recurve', 'AMBHR'),
('Adult Female Bowhunter Recurve', 'AFBHR'),
('Veteran Male Bowhunter Recurve', 'VMBHR'),
('Veteran Female Bowhunter Recurve', 'VFBHR'),
('Senior Male Bowhunter Recurve', 'SMBHR'),
('Senior Female Bowhunter Recurve', 'SFBHR'),
('Adult Male Bowhunter Unlimited', 'AMBU'),
('Adult Female Bowhunter Unlimited', 'AFBU'),
('Veteran Male Bowhunter Unlimited', 'VMBU'),
('Veteran Female Bowhunter Unlimited', 'VFBU'),
('Junior Female Freestyle Unlimited', 'JFFU'),
('Junior Male Freestyle Limited Recurve', 'JMFSR'),
('Cub Male Freestyle Unlimited', 'CMFU'),
('Adult Male Freestyle Limited Recurve', 'AMFSR'),
('Young Adult Male Bowhunter Recurve', 'YAMBHR');
