name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24.1

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./...

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Setup up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        service-account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for GCP
      run: gcloud auth configure-docker ${{ secrets.GCP_REGISTRY_LOCATION }}-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.GCP_REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY_NAME }}/hat-app:${{ github.sha }} -f ops/docker/Dockerfile .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.GCP_REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY_NAME }}/hat-app:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy hat-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/hat-app:${{ github.sha }} \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
